project:
  type: website
  output-dir: docs

website:
  title: "Milt-Hoke.com"
  navbar:
    right:
      - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    highlight-style: eiffel

editor: visual

